# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order_queue.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'order_queue.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11order_queue.proto\x12\x0border_queue\"[\n\x0e\x45nqueueRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x10\n\x08priority\x18\x02 \x01(\x05\x12%\n\x05items\x18\x03 \x03(\x0b\x32\x16.order_queue.OrderItem\"+\n\tOrderItem\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x61mmount\x18\x02 \x01(\x05\"\"\n\x0f\x45nqueueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x10\n\x0e\x44\x65queueRequest\"]\n\x0f\x44\x65queueResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x11\n\thas_order\x18\x02 \x01(\x08\x12%\n\x05items\x18\x03 \x03(\x0b\x32\x16.order_queue.OrderItem2\x9f\x01\n\x11OrderQueueService\x12\x44\n\x07\x45nqueue\x12\x1b.order_queue.EnqueueRequest\x1a\x1c.order_queue.EnqueueResponse\x12\x44\n\x07\x44\x65queue\x12\x1b.order_queue.DequeueRequest\x1a\x1c.order_queue.DequeueResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_queue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENQUEUEREQUEST']._serialized_start=34
  _globals['_ENQUEUEREQUEST']._serialized_end=125
  _globals['_ORDERITEM']._serialized_start=127
  _globals['_ORDERITEM']._serialized_end=170
  _globals['_ENQUEUERESPONSE']._serialized_start=172
  _globals['_ENQUEUERESPONSE']._serialized_end=206
  _globals['_DEQUEUEREQUEST']._serialized_start=208
  _globals['_DEQUEUEREQUEST']._serialized_end=224
  _globals['_DEQUEUERESPONSE']._serialized_start=226
  _globals['_DEQUEUERESPONSE']._serialized_end=319
  _globals['_ORDERQUEUESERVICE']._serialized_start=322
  _globals['_ORDERQUEUESERVICE']._serialized_end=481
# @@protoc_insertion_point(module_scope)
