# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: executor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'executor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xecutor.proto\x12\x08\x65xecutor\"$\n\x0f\x45lectionRequest\x12\x11\n\tsender_id\x18\x01 \x01(\x05\"\x1e\n\x10\x45lectionResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\">\n\x12\x43oordinatorRequest\x12\x11\n\tleader_id\x18\x01 \x01(\x05\x12\x15\n\rbecome_leader\x18\x02 \x01(\x08\":\n\x13\x43oordinatorResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x17\n\x0fprevious_leader\x18\x02 \x01(\x05\"%\n\x10HeartbeatRequest\x12\x11\n\tleader_id\x18\x01 \x01(\x05\"%\n\x11HeartbeatResponse\x12\x10\n\x08is_alive\x18\x01 \x01(\x08\"*\n\x0cWriteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\" \n\rWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1a\n\x0bReadRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1d\n\x0cReadResponse\x12\r\n\x05value\x18\x01 \x01(\x05\"\x0e\n\x0cStockRequest\"\"\n\rStockResponse\x12\x11\n\tall_items\x18\x01 \x03(\t2\x94\x03\n\x0f\x45xecutorService\x12\x41\n\x08\x45lection\x12\x19.executor.ElectionRequest\x1a\x1a.executor.ElectionResponse\x12J\n\x0b\x43oordinator\x12\x1c.executor.CoordinatorRequest\x1a\x1d.executor.CoordinatorResponse\x12\x44\n\tHeartbeat\x12\x1a.executor.HeartbeatRequest\x1a\x1b.executor.HeartbeatResponse\x12\x38\n\x05Write\x12\x16.executor.WriteRequest\x1a\x17.executor.WriteResponse\x12\x35\n\x04Read\x12\x15.executor.ReadRequest\x1a\x16.executor.ReadResponse\x12;\n\x08GetStock\x12\x16.executor.StockRequest\x1a\x17.executor.StockResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'executor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ELECTIONREQUEST']._serialized_start=28
  _globals['_ELECTIONREQUEST']._serialized_end=64
  _globals['_ELECTIONRESPONSE']._serialized_start=66
  _globals['_ELECTIONRESPONSE']._serialized_end=96
  _globals['_COORDINATORREQUEST']._serialized_start=98
  _globals['_COORDINATORREQUEST']._serialized_end=160
  _globals['_COORDINATORRESPONSE']._serialized_start=162
  _globals['_COORDINATORRESPONSE']._serialized_end=220
  _globals['_HEARTBEATREQUEST']._serialized_start=222
  _globals['_HEARTBEATREQUEST']._serialized_end=259
  _globals['_HEARTBEATRESPONSE']._serialized_start=261
  _globals['_HEARTBEATRESPONSE']._serialized_end=298
  _globals['_WRITEREQUEST']._serialized_start=300
  _globals['_WRITEREQUEST']._serialized_end=342
  _globals['_WRITERESPONSE']._serialized_start=344
  _globals['_WRITERESPONSE']._serialized_end=376
  _globals['_READREQUEST']._serialized_start=378
  _globals['_READREQUEST']._serialized_end=404
  _globals['_READRESPONSE']._serialized_start=406
  _globals['_READRESPONSE']._serialized_end=435
  _globals['_STOCKREQUEST']._serialized_start=437
  _globals['_STOCKREQUEST']._serialized_end=451
  _globals['_STOCKRESPONSE']._serialized_start=453
  _globals['_STOCKRESPONSE']._serialized_end=487
  _globals['_EXECUTORSERVICE']._serialized_start=490
  _globals['_EXECUTORSERVICE']._serialized_end=894
# @@protoc_insertion_point(module_scope)
